export const cardsData = [
  {
    'id': 0,
    'name': 'СURT Z30 Plus',
    'vendorCode': 'SO757575',
    'type': 'Acoustics',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-0.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 1,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-1.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 2,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-2.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 3,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-3.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 4,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-4.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 5,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-5.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 6,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-6.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 7,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-7.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
  {
    'id': 8,
    'name': 'Честер Bass',
    'vendorCode': 'SO757575',
    'type': 'electric',
    'description': 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    'previewImg': 'img/content/catalog-product-8.jpg',
    'stringCount': 7,
    'rating': 4,
    'price': 51100,
  },
];
